import { addDoc, collection, serverTimestamp } from "firebase/firestore"; // ? destructure the needed properties, to add document we use addDoc followed by collection. As the server timestamp is autogenerated
import { db } from "../config/firebase-config"; /// ? accessing the database firestore from config
import { useGetUserInfo } from "./useGetUserInfo"; // ? customhook to get the user infor stored in local storage

export const useAddTransaction = () => {
  /*
  ?  referencing the collection, the original syntax from documentation is 
  ? const docRef = await addDoc(collection(db, "users"), {});
  */

  const transactionCollectionRef = collection(db, "transactions");

  const { userID } = useGetUserInfo();

  // ? if this function called, it will return the Description, transaction amoung and type and then adding it to the collection.
  const addTransaction = async ({
    Description,
    transactionAmount,
    transactionType,
  }) => {
    await addDoc(transactionCollectionRef, {
      userID,
      Description,
      transactionAmount,
      transactionType,
      createdAt: serverTimestamp(),
    });
  };

  return { addTransaction }; // ? Returning the addTransction to use to the other components
};
